---
- hosts: all
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 86400
      become: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        pkg:
        - unzip
        - python3-pip
        state: latest
      become: yes

    - name: Install `fnm`, `node.js` and `yarn`
      ansible.builtin.include_role:
        name: hurricanehrndz.fnm
      vars:
        fnm_npm_global_packages:
          - name: yarn