name: Create WSLv1 image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_image:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MORAJLAB_MJI_PAT_TOKEN }}
          submodules: 'recursive'
      - name: Install distro
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          wsl-shell-user: mjl
          update: 'false'
          additional-packages: |
            unzip
      - name: Provision distro
        shell: wsl-bash -u root {0}
        run: |
          ./packages/provision/scripts/install.sh
          ./packages/provision/bin/provision.sh
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Export WSL image
        shell: pwsh
        run: |
          wsl --export Ubuntu mji-wsl-ubuntu-2004
      - name: Release distro image
        shell: pwsh
        run: |
          cd $env:USERPROFILE
          curl -#LO https://github.com/storj/storj/releases/latest/download/uplink_windows_amd64.zip
          Expand-Archive .\uplink_windows_amd64.zip
          cd .\uplink_windows_amd64\
          New-Item .\acc-grant.key
          echo "${{ secrets.MORAJLAB_STORJ_TOKEN }}" > .\acc-grant.key
          echo y|.\uplink.exe access import mji .\acc-grant.key
          .\uplink.exe cp .\mji-wsl-ubuntu-2004 sj://demo-bucket
