name: Create WSLv1 image
on:
  push:
    branches: ['monorepo']

jobs:
  create_image:
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - name: Install Ubuntu-20.04 distro
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          wsl-shell-user: mjl
      - name: Export WSL image
        shell: pwsh
        run: |
          wsl --export Ubuntu ubuntu-image
      - name: Provision distro
        run: |
          pwd
          ls -la
      - name: Release distro image
        uses: softprops/action-gh-release@v1
        with:
          files: ubuntu-image
